### ISSUE TITLE
Feature Request:  Custom Entry Name

### ISSUE THREAD

**Issue by HippyCraig** [ardittristan/VTTInlineWebviewer#1]
I think it would be nice to have a field in the settings to change the name of the journal entry from "Containers" to something custom that may make more sense to the individual GM.

Also if the Journal Entry option is selected and the custom name filled in maybe have it create the entry if it doesn't exist.

**Comment by ardittristan** [comment]
I'll add the first one in the next update, I don't think the auto creation is a good idea tho since it could cause unwanted journal creations.

**Comment by HippyCraig** [comment]
Great!!   Thanks for considering this, but I agree I can see how that auto creation can get messy.  :)

**Comment by HippyCraig** [comment]
Works like a charm!!!
