### ISSUE TITLE
Exported journal entry is empty

### ISSUE THREAD

**Issue by cwlithgow** [ardittristan/VTTInlineWebviewer#14]
Saw the module featured on Scabards website and it is what convinced me to migrate to Foundry.

I'm able to launch a website from within the native foundry app, or from within Chrome - with or without the browser extension or compatibility mode. When I export it - the journal entry is created, but with no content.

Any insight?
![Foundry Virtual Tabletop • A Standalone Virtual Tabletop Application - Google Chrome 2021-05-29 12-37-12](https://user-images.githubusercontent.com/85030999/120078166-1a9e6d00-c07c-11eb-8a17-ce84b953b599.gif)

**Comment by ardittristan** [comment]
Can you try with the latest version?

**Comment by cwlithgow** [comment]
That did the trick - Thanks!
