### ISSUE TITLE
[Bug] Icons are not showing well

### ISSUE THREAD

**Issue by brunocalado** [ardittristan/VTTInlineWebviewer#16]
Hi.

I can't make icons show.

Can you create a file picker to it?

Thank you.

**Comment by pesky-wobbit** [comment]
Same here - my assets path is correct. Yes: File Picker would be handy.

**Comment by ardittristan** [comment]
Sorry, didn't see the issue. I'll take a look!

**Comment by ardittristan** [comment]
The side bar currently only supports font awesome (or any other installed icon fonts) icons.

There should be a help button on the top of the settings menu:  
![image](https://user-images.githubusercontent.com/42787508/128223760-8a433272-98e6-49fd-adfd-01b02b4acc21.png)

Here it's explained how to get an icon name:  
![image](https://user-images.githubusercontent.com/42787508/128223175-8a4d5cd7-4dff-4a1a-b494-47665ba6b2f6.png)
