### ISSUE TITLE
Can't get macro script to work! Please help!

### ISSUE THREAD

**Issue by DanielRonnstam** [ardittristan/VTTInlineWebviewer#17]
Hi. Could you please explain better how I should use the Macro script? I can't get it to work but I can't code. What have I done wrong here?...

/**
 * @param {String} url - webview url
 * @param {Boolean} compat - compatibility mode on or off
 * @param {Number} w - width
 * @param {Number} h - height
 * @param {String} name - title of application
 * @param {String} customCSS - css selectors for elements to be removed, comma seperated
 * @param {String[]} userList - array of user id's to which the webview gets send, if empty it sends to everyone
 * @param {String} properties - string of html element properties to add to the iframe element
 */
window.Ardittristan.InlineViewer.sendUrl(https://docs.google.com/spreadsheets/d/1zP9s5kt9CTpOm4qYrzT2LIblNfL28SxqCKlk7KmpBbQ/edit?usp=sharing, compat = false, w = 1000, h = 1500, Conflict Resolve,,,)

**Comment by DanielRonnstam** [comment]
I want to display a section of a google spreadsheet in the inline window, to get rid of the menu and stuff in the upper and left corners. Is this possible? If so, what would the macro script for this be?

**Comment by ardittristan** [comment]
normal:  
```js
window.Ardittristan.InlineViewer.sendUrl("https://docs.google.com/spreadsheets/d/1zP9s5kt9CTpOm4qYrzT2LIblNfL28SxqCKlk7KmpBbQ/edit?usp=sharing", false, 1000, 1500, "Conflict Resolve..." );
```

with hidden header:
```js
window.Ardittristan.InlineViewer.sendUrl("https://docs.google.com/spreadsheets/d/1zP9s5kt9CTpOm4qYrzT2LIblNfL28SxqCKlk7KmpBbQ/edit?usp=sharing", true, 1000, 1500, "Conflict Resolve...", "#docs-chrome {display: none;}");
```

**Comment by ardittristan** [comment]
strings should be enclosed with quotes, and the = signs suggest that that's the default value

**Comment by DanielRonnstam** [comment]
Thanks!! will check

**Comment by DanielRonnstam** [comment]
It opens, and looks nice, but I would want to only show the area in the red square in the image below. Is this possible?

![image](https://user-images.githubusercontent.com/48160813/130480279-3d115eef-588b-4c7a-abb4-56741e396135.png)

**Comment by ardittristan** [comment]
best I can get is this:
```js
window.Ardittristan.InlineViewer.sendUrl("https://docs.google.com/spreadsheets/d/1zP9s5kt9CTpOm4qYrzT2LIblNfL28SxqCKlk7KmpBbQ/edit?usp=sharing", true, 1000, 1500, "Conflict Resolve...", "#docs-chrome, div[role=navigation] {display: none;}");
```

**Comment by DanielRonnstam** [comment]
ok thanks!
