### ISSUE TITLE
Cannot Get Inline viewer to function in Foundry

### ISSUE THREAD

**Issue by brithon** [ardittristan/VTTInlineWebviewer#18]
Inline viewer box pops up with blank grey background and no browser viewer when putting in URL's. Have tried all recommended fixes, compatibility mode, chrome extension fix, disabling anti-virus.  Attempted with both Chrome and Brave as default browsers.  Nothing appears to resolve.  Running private server on home client.  What am I missing here?

**Comment by ardittristan** [comment]
what website are you trying to load?

**Comment by brithon** [comment]
Every URL. it doesn't matter.  Just the grey field appears in the pop-up, no browser content.

**Comment by ardittristan** [comment]
any errors in the dev console? (F12)

**Comment by brithon** [comment]
Yes, Here is one for an attempt at a youtube URL "Refused to display 'https://www.youtube.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'."

**Comment by ardittristan** [comment]
which should be normal, and fixable with the proxy. But I'm noticing the proxy isn't working atm, let me try to restart it!

**Comment by ardittristan** [comment]
compatibility mode should work again!
could you recheck youtube with compatibility mode on?

**Comment by brithon** [comment]
Excellent that worked to load standard webpages!  Couldn't proxy video play on youtube however, or play embedded video on web pages.  Just gives an error on the video stream.

**Comment by ardittristan** [comment]
youtube sadly only works with the browser extension
