### ISSUE TITLE
Language issue

### ISSUE THREAD

**Issue by ollster76** [ardittristan/VTTInlineWebviewer#2]
I have a google doc that I used your excellent module (v1.3.2) to access from within Foundry v0.6.4. Unfortunately the link renders the GDoc UI in some sort of Germanic language.

The document itself is in English (UK). I tested with my primary browser (Vivaldi) and also straight Google Chrome, with the same result in both, and both browsers are up to date and both are using some variant of English, same with the underlying client and server OS.

Thanks!

**Comment by ardittristan** [comment]
This is because compatibility mode uses a proxy hosted on a german-based amazon aws instance. There should be an option in google docs to change the ui language.

**Comment by ardittristan** [comment]
I could take a look at the `Accept-Language` header tomorrow to see if i can default it to English with it.

**Comment by ardittristan** [comment]
Couldn't fix it with the header. But moved the server to a UK location instead of Germany so it should default to English now.

**Comment by ollster76** [comment]
Thanks very much, I really appreciate this!
