### ISSUE TITLE
Feature Request: webview as scene

### ISSUE THREAD

**Issue by Dr-KerbalMD** [ardittristan/VTTInlineWebviewer#24]
Would love to be able to  make a scene a webview for quicker access. Mainly so I could leave https://scribbletogether.com/ on that scene as a persistent whiteboard.

**Comment by dukayn** [comment]
I know this is old, but how on earth do you get a scene webview to load? Like I've set it up in the settings and everything, but there's no documentation on how to actually get a scene to load the webview that I can find.
