### ISSUE TITLE
Macro call to open window for current user not working

### ISSUE THREAD

**Issue by skepickle** [ardittristan/VTTInlineWebviewer#25]
If I try to call .sendUrl() using a userList, the call just does nothing and also logs no errors to the browser console. If I remove the userList argument completely, the call works but obviously opens the window for all users.

```
// Doesn't Work:
window.Ardittristan.InlineViewer.sendUrl("https://www.blahblah.com/blah", true, 1200, 800, "Blah", "", [game.userId])

// Works:
window.Ardittristan.InlineViewer.sendUrl("https://www.blahblah.com/blah", true, 1200, 800, "Blah", "")
```

I've obviously copy/pasted a fake URL above, you get the jist though.

Foundry Virtual Tabletop version 9, build 238
System: "3.5e SRD" version 0.98.9

The only two modules active are "Inline Webviewer" and "lib - Color Settings".

What am I doing wrong here?

**Comment by ardittristan** [comment]
ah, v9 removed a value that was being read to check if the sender of the api method also needed to have the webview open. Fix coming right away!
