### ISSUE TITLE
Compatibility mode does not work

### ISSUE THREAD

**Issue by sirgawain111** [ardittristan/VTTInlineWebviewer#29]
With compatibility mode turned on for a web page, the module tries to connect to a web address starting with https://cors-anywhere.ardittristan.xyz:9123/vtt/INTENDED-WEB-PAGE, and that does not work.

**Comment by ardittristan** [comment]
the cors-anywhere proxy only works inside foundry, so going to there in your normal browser shouldn't work.
It might be that the site still won't work with the proxy, in which case https://github.com/ardittristan/FoundryVTT-Inline-Webviewer-Extension could work.

if you're fine with sending the intended url I can check if this is the case (even if it's just the url of the home page of the site)

**Comment by sirgawain111** [comment]
Thanks for your quick response.
It's kind of weird because the site worked inside Foundry until the last update. Unfortunately, I also updated lots of other modules, so maybe it's one of those who causes the issue.
URL is https://ulisses-regelwiki.de/start.html
When trying to connect I get the message, that the site may be temporarily unavailable or may have been permanently moved to a new web address.
Any help appreciated.

**Comment by ardittristan** [comment]
The proxy crashed, restarted and made it automatically restart once/day, should be fixed now!

**Comment by sirgawain111** [comment]
Thanks a lot!
