### ISSUE TITLE
Module does not work on v10.291 foundry

### ISSUE THREAD

**Issue by AwesomeTeo** [ardittristan/VTTInlineWebviewer#35]
It just does not showed up in the menu, old journal notes created with it also does not working. I'm using v3.4.2 VTTInlineWebviewer.
Is there a chance you will make new version of it?

**Comment by ardittristan** [comment]
should work again, was an issue with the proxy

**Comment by AwesomeTeo** [comment]
No. I tried to reinstall it, but again - no module icon in left menu at all and also old journal entrys does not working. I can see settings of the module in game settings menu. Btw I'm using foundry on forge-vtt.com can it be the problem? (it worked there for a long time, I don't know exactly when it broke)

**Comment by AwesomeTeo** [comment]
Ok I disabled all other modules and webviewver showed up in menu. It is partly working. But still old journal notes are broken, so as new ones.
![Снимок экрана_20230205_231557](https://user-images.githubusercontent.com/108455964/216868592-05bae598-0aea-42b9-9329-4e97fe15b5c3.png)
![Снимок экрана_20230205_231620](https://user-images.githubusercontent.com/108455964/216868606-dd7b9afe-8e8d-41d1-860c-4de5ab66c826.png)
![Снимок экрана_20230205_231644](https://user-images.githubusercontent.com/108455964/216868799-f0ae7405-00eb-4438-bbeb-7226fc1dca67.png)

**Comment by ardittristan** [comment]
What system are you using? I'll take a look at it wednesday or this weekend!

**Comment by AwesomeTeo** [comment]
Tnx! D&D 5e v. 2.1.2

**Comment by ardittristan** [comment]
should be fixed!

**Comment by AwesomeTeo** [comment]
nope, still have the same problem =(
