### ISSUE TITLE
depreciated fields?

### ISSUE THREAD

**Issue by spookymonster** [ardittristan/VTTInlineWebviewer#38]
![image](https://user-images.githubusercontent.com/16195156/226071720-d090c419-5d78-4a13-86cd-9e5dcbeee17d.png)

**Comment by mrjaksauce** [comment]
Here's my updated code while I wait for the author to fix, I've simply replaced, or removed unnecessary, deprecated stuff:

`{
    "id": "inlinewebviewer",
    "title": "Inline Webviewer",
    "description": "Have a webpage open inside Foundry, eg an easyzoom map.",
    "authors": [
	{
		"name": "ardittristan0001",
		"flags": {}
	}
	],
    "url": "https://github.com/ardittristan/VTTInlineWebviewer",
    "version": "3.5",
	"compatibility": {
		"minimum": "10",
		"verified": "10"
  },
    "scripts": [
        "./lib/colorSettingStub.js"
    ],
    "esmodules": [
        "inlineviewer.js"
    ],
    "styles": [
        "./css/inlineviewer.css"
    ],
    "languages": [
        {
            "lang": "en",
            "name": "English",
            "path": "lang/en.json"
        },
        {
            "lang": "ja",
            "name": "日本語",
            "path": "lang/ja.json"
        }
    ],
    "packs": [],
    "socket": true,
    "manifest": "https://raw.githubusercontent.com/ardittristan/VTTInlineWebviewer/master/module.json",
    "download": "https://github.com/ardittristan/VTTInlineWebviewer/releases/download/3.4.2/inline-viewer.zip",
    "protected": false,
    "coreTranslation": false,
    "library": false
}`

**Comment by mrjaksauce** [comment]
Note: I do not think this will work for v9. I have not tested it.

**Comment by ardittristan** [comment]
This is mostly done to stay backwards compatible, it has both the old and new manifest fields
