### ISSUE TITLE
Package updates but never moves past 3.4.2

### ISSUE THREAD

**Issue by solarflair** [ardittristan/VTTInlineWebviewer#39]
When running an update in the Foundry web interface, VTTInlineWebviewer always updates but never actually moves from 3.4.2 to 3.4.3. I don't know if it's a module problem or a Foundry problem, but this is the only module that this happens with so I lean towards it being the module.

Foundry 10 build 291 (latest) on a RHEL 9.1 server.

Screenshot: https://i.imgur.com/KydIdio.png

**Comment by velinion** [comment]
Can confirm. Same experience here (Running felddy's Docker instance on a Debian system) in both Foundry 10 and 11. Uninstalling the module and then reinstalling resulted in a reported InlineWebViewer 3.4.2 being installed (Which updates to 3.4.2 every time I check for updates, same as before.) 
I'm wondering if the installed version is actually 3.4.3 and it's just reporting its version number wrong, resulting in it being re-downloaded every time an update check is made?

**Comment by sharcashmo** [comment]
I think it is caused because in module.json file the  'download' field links to 3.4.2 release file, instead of 3.4.3. So it is 3.4.2 what is always installed.
