### ISSUE TITLE
Players see 2 Close windows on Inline Webviewer windows

### ISSUE THREAD

**Issue by DaveParkinglot** [ardittristan/VTTInlineWebviewer#45]
![Screenshot 2024-02-19 103332](https://github.com/ardittristan/VTTInlineWebviewer/assets/159180002/8dcbe921-6420-43f1-a008-9bb7a58a2832)

I also noticed the window name doesn't seem to use the "name" argument from the macro.

**Comment by ardittristan** [comment]
I'll probably have time to look at it next weekend

**Comment by ardittristan** [comment]
what other modules/system are you running? I'm not able to replicate

**Comment by DaveParkinglot** [comment]
I'm running this. The above screenshot in my most was me running only Inline Webviewer and dependencies. It only seemed to affect player accounts, and it only happened on windows opened from the Webview sidebar...
![image](https://github.com/ardittristan/VTTInlineWebviewer/assets/159180002/301ee3d4-3ede-4b65-81e3-878211e05653)
