### ISSUE TITLE
Alert issue

### ISSUE THREAD

**Issue by Tarrith** [ardittristan/VTTInlineWebviewer#7]
I'm getting a (suspected) alert from Avast Antivirus when I activate VTTInlineWebviewer :(

![Alert](https://user-images.githubusercontent.com/23333805/103021240-f48d1200-459d-11eb-8866-24f7a200b975.jpg)

**Comment by ardittristan** [comment]
that might be because the iframe uses a proxy to pass through websites in compatibility mode, there isn't much I can do about it though, since if used maliciously this kind of proxy can be used to extract data so I don't think avast will whitelist it.

**Comment by Tarrith** [comment]
I wasn't using compatibility mode.

**Comment by ardittristan** [comment]
hm, then it might be because I listen to the iframe in
```js
// listen for iframes
  window.addEventListener("message", (e) => {
    if (typeof e.data !== "string") return;

    let element = $(`iframe#${e.data}`);

    if (!(element.length > 0)) return;

    element.each(function () {
      this.contentWindow.postMessage(this.dataset.customcss, "*");
    });
```
with the any origin tag? otherwise I have no idea

**Comment by Tarrith** [comment]
The previous version worked fine if that's any help.

**Comment by ardittristan** [comment]
well, I haven't changed anything with the iframe since 2.0.1, so I think it's just a false positive

**Comment by Tarrith** [comment]
Well that sucks :\
I hate false positives.
