### ISSUE TITLE
Share button shares just the base address

### ISSUE THREAD

**Issue by luizbgomide** [ardittristan/VTTInlineWebviewer#8]
When I share something I want to share what I'm currently viewing, but the Share button just fills the address set in the starting webview.

Is there a way to share the current address I'm viewing?

**Comment by ardittristan** [comment]
Sadly that is not possible. Because of browser security it's not possible to see the content of an iframe (what inline webviewer uses). So I can't extract the current url from it, only the initial url since that's in the iframe properties and not the content of the iframe.
