### ISSUE TITLE
After first time closing cannot reopen

### ISSUE THREAD

**Issue by Ashirra** [ardittristan/VTTInlineWebviewer#9]
Hello

First thank you for your module.

**Issue**
After clicking on a journal entry with an embedded url it works perfectly fine.
When closing and reopening then it won't show up.

**_As a GM_**
Reaplying the url and then it works again.
-- works not always. Selecting another journal entry then it works again.

_**As a Player**_
Only F5 works

**Comment by ardittristan** [comment]
could you maybe send me the url and the settings you have enabled when exporting to journal?
if it's a sensitive url feel free to dm it to me on discord! `ardittristan#0001`

**Comment by Ashirra** [comment]
https://www.dnddeutsch.de/schnellreferenz/?m
What do you mean with settings? Could you be little bit more precise?

**Comment by ardittristan** [comment]
![image](https://user-images.githubusercontent.com/42787508/110545813-f3479c00-812d-11eb-850c-8ca5cc81c348.png)
With settings I meant compat mode or not.
As for the url, it seems to work fine for me when exported to journal. Both in the foundryvtt application and in the chromium browser. (compat mode off)

Is there any kind of error in the console when it doesn't work? (F12)

**Comment by Ashirra** [comment]
This was a problem with Avast antivir.
